# Use a compatible Python version
FROM python:3.12.1-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
# COPY requirements.txt .

# Install dependencies
# RUN pip install --no-cache-dir -r requirements.txt
RUN pip install streamlit langchain fitz SpeechRecognition gtts langchain-community langchain-chroma

# Copy the rest of the application code
COPY . .

# Expose the port your app will run on
EXPOSE 8501

# Command to run the application
CMD ["python", "app.py"]
